### ISSUE TITLE
Consider adding dns to PortBackendConfig

### ISSUE THREAD

**Issue by andrewwebber** [zlabjp/nghttpx-ingress-lb#17]
Without [DNS](https://nghttp2.org/documentation/nghttpx-howto.html#dynamic-hostname-lookup) activated my understanding would be that scaling services becomes and issue (if we want to bypass the kube-proxy).

```yaml
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  clusterIP: None
  ports:
  - name: http
    port: 1984
  selector:
    app: grpc-server
```
