### ISSUE TITLE
Does this lb support traefik's PathPrefixStrip like feature

### ISSUE THREAD

**Issue by charandas** [zlabjp/nghttpx-ingress-lb#85]
In traefik, I can annotate with something like `traefik.someApi.frontend.rule: 'PathPrefixStrip:/some-prefix'`, and the load balancer will match on the path with the prefix `some-prefix`, but will strip it before forwarding it to the container.

Tried this [resource](https://nghttp2.org/documentation/nghttpx.1.html) but cannot find something related, that I could use with:

```
data:
  nghttpx-conf: |
```

For my use case, need to be able to strip `filing`, `public` and `admin` from all three rules below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hmda-platform-ingress
  annotations:
    ingress.zlab.co.jp/backend-config: '{"hmda-platform-api": {"transport": {"proto": "h2"}}}'
spec:
  rules:
  - http:
      paths:
      - path: /hmda/filing
        backend:
          serviceName: hmda-platform-api
          servicePort: filing
      - path: /hmda/admin
        backend:
          serviceName: hmda-platform-api
          servicePort: admin
      - path: /hmda/public
        backend:
          serviceName: hmda-platform-api
          servicePort: public
```

**Comment by charandas** [comment]
@tatsuhiro-t thanks for your comment. Yes, that is correct, I need to rewrite path after determining backend service.

Do you mean to say that when mruby script executes, the backend service has not yet been determined based on path matching, so rewriting path there would cause it to fail the match?

I may have to modify the application code itself to honor the prefix if I cannot strip it.

**Comment by charandas** [comment]
Also, maybe there is the possibility of defining the matching paths to just be filing, public and admin in my example, but let consumers use the prefix.

Then, in the mruby script, rewrite path to not have prefix. Then path matching should pass.

**Comment by tatsuhiro-t** [comment]
> Do you mean to say that when mruby script executes, the backend service has not yet been determined based on path matching, so rewriting path there would cause it to fail the match?

Yes

> Also, maybe there is the possibility of defining the matching paths to just be filing, public and admin in my example, but let consumers use the prefix.
>
> Then, in the mruby script, rewrite path to not have prefix. Then path matching should pass.

I think it works.  You might need to do some actions to prevent consumer from accessing /public directly in mruby if it is required.

**Comment by charandas** [comment]
@tatsuhiro-t thanks for trying to help out. It seems any kind of mruby manipulation of the path ends up dictating later decision making of choosing the backend fail in my case. My line of thought would only work if mruby kicked in after backend was chosen.

In any case, I got this to work for my use-case:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hmda-platform-ingress
spec:
  rules:
  - host: 'filing.myhmdaapp.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: hmda-platform-api
          servicePort: filing
  - host: 'admin.myhmdaapp.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: hmda-platform-api
          servicePort: admin
  - host: 'public.myhmdaapp.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: hmda-platform-api
          servicePort: public
```

Then accessing whichever one using the correct `Host` headers.

```
curl -H "Host: filing.myhmdaapp.com" -i http://ingress-address
```

Closing this issue for now.
